// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Maq9_JwK9gEaKAyC1-CDc995LlA2cPY',
    appId: '1:323116488555:web:04ea5be4983471efb15e2e',
    messagingSenderId: '323116488555',
    projectId: 'project-673480bf-b9b8-4e5b-8a1',
    authDomain: 'project-673480bf-b9b8-4e5b-8a1.firebaseapp.com',
    storageBucket: 'project-673480bf-b9b8-4e5b-8a1.firebasestorage.app',
    measurementId: 'G-J8TLQ4KG5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1PBGC-VJi4koP0FAXSZyPZjKKxtt6oQs',
    appId: '1:323116488555:android:9764f97cbf9e29bfb15e2e',
    messagingSenderId: '323116488555',
    projectId: 'project-673480bf-b9b8-4e5b-8a1',
    storageBucket: 'project-673480bf-b9b8-4e5b-8a1.firebasestorage.app',
  );
}
